# The URL of your instance
# It is highly recommeded to run this script where your lemmy server is hosted to bypass nginx rate limit
local_instance_url = "ip:port"

# An array of remote instances you would like to pull top communities from
# If left empty the instances will be pulled from https://raw.githubusercontent.com/maltfield/awesome-lemmy-instances/main/awesome-lemmy-instances.csv
remote_instances = []

# The number of top communities to pull from each instance. -1 Means pull everything
community_count = 50

# The sort methods you would like to search by https://join-lemmy.org/api/types/SortType.html
community_sort_method = "Active"

# Skips all the communities for the instances in the list
# Only include domain and tld or if it contains subdomain(s)
skip_instances = [
    "hexbear.net"
]

# Skips the instances with monthly active user count below this number
minimum_monthly_active_users = 10

# Skips all the communities in the list. Format: !community_name@domain.tld
skip_communities = [
    "!games@hexbear.net"
]

# Maximum number of cocurrent connections to fetch data and subscribe
max_workers = 2

# How long to sleep after adding a new community to your instance
seconds_after_community_add = 5

# To add or not to add NSFW communities
skip_nsfw = false
